### PR TITLE
[AP-3834] add working Dockerfile and docker-compose

### PR DESCRIPTION
**Pull request by jsugarman**
## What
Add a dockerfile and test locally with docker compose

[Link to story](https://dsdmoj.atlassian.net/browse/AP-3834)

Amend the DfE Dockerfile template and try out the
build of it using docker-compose.

Based on a few different Dockerfiles, including
other apply service area versions, this:

1. uses 3 images to optimize caching
2. ignores and/or removes unneeded files to minimize image size
3. breaks up layers in an attempt to optimise caching for most common future changes
4. add pingable endpoint data

## Checklist

Before you ask people to review this PR:

- Tests and linters should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Comment by cpjmcquillan** [comment]
Sorry to bring grim reaper levels of pessimism on a Monday morning, but have we asked ourselves if we _really_ want to maintain a `docker-compose.yml` file?

Maybe I'm missing context, but I was under the impression we were optimising for ease of maintenance.

**Comment by jsugarman** [comment]
> Sorry to bring grim reaper levels of pessimism on a Monday morning, but have we asked ourselves if we _really_ want to maintain a `docker-compose.yml` file?
> 
> Maybe I'm missing context, but I was under the impression we were optimising for ease of maintenance.

As mentioned din the comment this is/has been useful in testing the build locally. It is not for production build and deploy. 

It is allows us to test build issues, optimisations locally without incurring time, cost, inefficiencies of CI runs. In addition, if not deemed useful, it can always be thrown away easily. I find it useful at present

**Review by kmahern — APPROVED** [review]
As discussed, I seem to be (intermittently?) having an issue with assets/css not being available when running docker compose up and then open http://0.0.0.0:3000. I will approve anyway as I have not always been able to recreate and this may or may not be an issue when we deploy to a kubernetes namespace.

**Comment by jsugarman** [comment]
> As discussed, I seem to be (intermittently?) having an issue with assets/css not being available when running docker compose up and then open http://0.0.0.0:3000. I will approve anyway as I have not always been able to recreate and this may or may not be an issue when we deploy to a kubernetes namespace.

I have pushed a changed to the Dockerfile which seems to work for me. can you try and let me know.

**Pull request merged**
