### PR TITLE
Add i18n-tasks gem and configure

### PR DESCRIPTION
**Pull request by jsugarman**
## What
Add i18n-tasks with config and specs

Since we are using translations we should
test for, at least, no missing keys and unused
keys. keys being normalized and "consistent" interpolation
test has been added too for now.

## Checklist

Before you ask people to review this PR:

- Tests and linters should be passing: `bundle exec rake`
- Github should not be reporting conflicts; you should have recently run `git rebase main`.
- There should be no unnecessary whitespace changes. These make diffs harder to read and conflicts more likely.
- The PR description should say what you changed and why, with a link to the JIRA story.
- You should have looked at the diff against main and ensured that nothing unexpected is included in your changes.
- You should have checked that the commit messages say why the change was made.

### CODE REVIEW

**Review by kmahern — APPROVED** [review]
👍

**Review by cpjmcquillan — COMMENTED** [review]
Does this align with our plan to minimise dependencies?

**Comment by jsugarman** [comment]
> Does this align with our plan to minimise dependencies?

it is certainly one i would consider important if we are to use translations.

**Comment by cpjmcquillan** [comment]
> > Does this align with our plan to minimise dependencies?
> 
> it is certainly one i would consider important if we are to use translations.

If `config.i18n.raise_on_missing_translations = true` in test and we have appropriate coverage, then we're only really highlighting unused translations —which I wouldn't consider vital (especially in the context of wanting to minimise dependencies)

**Pull request merged**
